### ISSUE TITLE
URL suggestion for Julia compiler

### ISSUE THREAD

**Issue by waldyrious** [mohd-akram/compilers#3]
The code for Julia-to-LLVM IR compilation is not neatly packaged into a single directory or file, but there's a nice overview in the docs: http://docs.julialang.org/en/latest/devdocs/llvm/#overview-of-julia-to-llvm-interface

I'm not sure this link would be adequate for the url field in the metadata, but I thought I'd put the suggestion out there.

**Comment by mohd-akram** [comment]
Given that it is the default compiler for Julia and it is mentioned on the homepage, I think the current link is sufficient.

**Comment by waldyrious** [comment]
Are you referring to the section "High-Performance JIT Compiler" in http://julialang.org? Yeah, sounds fair.

**Comment by mohd-akram** [comment]
Yup.
